version: "3.7"
services:
    web:
        image: nginx:latest
        ports:
            - "${WEB_PORT}:80"
        volumes:
            - ./silverstripe:/application
            - ./docker/nginx/web.conf:/etc/nginx/conf.d/web.conf

    app:
        build: docker/php-fpm
        volumes:
            - ./silverstripe:/application
            #- ./docker/php-fpm/php-ext-xdebug-overrides.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment:
          XDEBUG_CONFIG: "remote_host=${LOCAL_IP} remote_port=${XDEBUG_REMOTE_PORT}"

    database:
        image: mysql:5.6
        volumes:
          - ./docker/db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=abc123
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=dev_user
            - MYSQL_PASSWORD=dev_passwd
        ports:
            - "${MYSQL_PORT}:3306"
